#!/usr/bin/env bash
# Creates PID file, loops indefinitely, handles signals
echo $$ > /var/run/myscript.pid

function clean_up {
    rm -f /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command"; clean_up' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'clean_up' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
